@extends('layouts.app')
@section('content')
<section class="branding-agency-hero aci-hero"><div class="container">
<div class="hero-eyebrow"><span class="status-dot"></span> VOTRE PARTENAIRE INFORMATIQUE À DAKAR <span class="hero-index">01 — ACI INFORMATIQUE</span></div>
<div class="hero-content"><h1 class="hero-title"><span>Performance.</span><br><span>Sécurité.</span><br><span class="outline-word">Sérénité.</span></h1><img class="hero-star" src="{{ asset('assets/img/star-of-life.svg') }}" alt="" aria-hidden="true"><div class="hero-aside"><p>Une informatique fiable.<br>Des équipes mieux connectées.<br>Une entreprise qui avance.</p><a class="round-link" href="#expertises" aria-label="Découvrir nos expertises">↘</a></div></div>
<div class="hero-bottom"><span>SYSTÈMES & RÉSEAUX <b>✳</b> CLOUD <b>✳</b> CYBERSÉCURITÉ</span><a href="#contact">Donnons vie à votre projet <span>↗</span></a></div>
</div></section>
<div class="aci-visual"><img src="{{ asset('images/122658.webp') }}" alt="Espace de travail équipé d’outils informatiques et d’analyse" fetchpriority="high"><div class="visual-caption"><span>La technologie, avec un accompagnement humain.</span><span>DAKAR, SÉNÉGAL ↗</span></div></div>
<section id="apropos" class="section-space"><div class="container about-grid"><div><p class="eyebrow">01 / QUI SOMMES-NOUS ?</p><h2>Votre informatique.<br>Notre <em>engagement.</em></h2></div><div class="about-copy"><p class="lead-copy">Un système d’information performant et sécurisé, pour vous concentrer sur l’essentiel.</p><p>ACI Informatique accompagne les entreprises, PME, écoles, ONG et institutions dans leur transformation numérique. Nous concevons des solutions fiables, adaptées à vos besoins opérationnels et à votre budget.</p><a class="text-link" href="#contact">Faisons connaissance <span>↗</span></a></div></div><div class="container audiences"><span>À VOS CÔTÉS</span><span>Entreprises & PME</span><span>Écoles</span><span>ONG</span><span>Institutions</span></div></section>
<section id="expertises" class="expertise-section section-space"><div class="container"><div class="section-top"><div><p class="eyebrow">02 / NOS EXPERTISES</p><h2>Les bonnes solutions.<br>Au bon <em>endroit.</em></h2></div><p>Du poste de travail au cloud,<br>un accompagnement à chaque étape.</p></div>
@foreach(config('aci.services') as $slug => $service)
<article class="branding-service-item aci-service {{ $loop->even ? 'service-light' : 'service-dark' }}"><div class="branding-service-wrap"><div class="branding-service-info"><span class="service-kicker">{{ str_pad($loop->iteration, 2, '0', STR_PAD_LEFT) }} / EXPERTISE</span><h3><a href="{{ route('services.show', $slug) }}">{{ $service['title'] }}</a></h3><p>{{ $service['description'] }}</p><a class="service-link" href="{{ route('services.show', $slug) }}">Découvrir cette expertise <span>↗</span></a></div><span class="count">/{{ str_pad($loop->iteration, 2, '0', STR_PAD_LEFT) }}</span></div><div class="service-thumb-wrap"><img src="{{ asset('images/'.$service['image'].'.webp') }}" alt="{{ $service['title'] }}" loading="lazy"><div class="image-label">{{ $service['short'] }}</div></div></article>
@endforeach
</div></section>
<section class="section-space commitments"><div class="container"><div class="section-top"><div><p class="eyebrow">03 / NOTRE FAÇON DE TRAVAILLER</p><h2>La confiance se construit.<br><em>Chaque jour.</em></h2></div><p>Des engagements concrets,<br>à chaque intervention.</p></div><div class="commitment-grid">
@foreach(['Réactivité' => 'Une prise en charge professionnelle de vos demandes.', 'Personnalisation' => 'Des solutions adaptées à votre organisation et à votre budget.', 'Sécurité' => 'La confidentialité et la protection de vos données.', 'Qualité' => 'Une documentation claire et des utilisateurs accompagnés.', 'Proximité' => 'Un interlocuteur disponible et à votre écoute.', 'Évolution' => 'Une veille technologique et une amélioration continue.'] as $title => $text)
<div><span class="commitment-number">0{{ $loop->iteration }} ↗</span><h3>{{ $title }}</h3><p>{{ $text }}</p></div>
@endforeach
</div></div></section>
<section id="offres" class="section-space offers-section"><div class="container"><div class="section-top"><div><p class="eyebrow">04 / NOS OFFRES</p><h2>Un besoin précis.<br>Une offre <em>adaptée.</em></h2></div><p>Des bases transparentes.<br>Une proposition selon votre périmètre.</p></div><div class="price-list">
@foreach(config('aci.services') as $slug => $service)
<a class="price-row" href="{{ route('home', ['service' => $slug]) }}#contact"><span class="price-index">0{{ $loop->iteration }}</span><h3>{{ $service['title'] }}</h3><div class="price">@if($service['price'])<small>À partir de</small><strong>{{ $service['price'] }} <span>{{ $service['period'] }}</span></strong>@else<small>Selon votre projet</small><strong>Sur devis</strong>@endif</div><span class="price-arrow">↗</span></a>
@endforeach
</div><p class="price-note">Tarifs indicatifs, variables selon le nombre d’utilisateurs, les équipements, la complexité, les déplacements et les prestations retenues. Le devis définitif est établi après analyse de votre besoin.</p><details class="conditions"><summary>Les conditions de votre accompagnement <span>+</span></summary><p>Validité de l’offre : 30 jours. Délai d’exécution : selon le périmètre et le planning convenus. Paiement : 50 % à la commande et 50 % à la livraison. Support après livraison : selon la prestation ou le contrat de maintenance.</p></details></div></section>
<section id="contact" class="section-space contact-section"><div class="container contact-grid"><div><p class="eyebrow">05 / PARLONS DE VOTRE PROJET</p><h2>Et si on faisait<br>avancer votre<br><em>informatique ?</em></h2><p>Décrivez-nous votre besoin.<br>Construisons une solution adaptée.</p><div class="contact-person"><span class="person-icon">↗</span><div><strong>Oumar Sow</strong><span>Votre interlocuteur · Dakar, Sénégal</span></div></div><div class="contact-links">@if(config('aci.email'))<a href="mailto:{{ config('aci.email') }}">{{ config('aci.email') }} <span>↗</span></a>@endif @if(config('aci.phone'))<a href="tel:{{ preg_replace('/[^+0-9]/', '', config('aci.phone')) }}">{{ config('aci.phone') }} <span>↗</span></a>@endif</div></div>
<form method="POST" action="{{ route('contact.store') }}" class="contact-form">@csrf
@if(session('success'))<div class="notice success" role="status">{{ session('success') }}</div>@endif
@if($errors->any())<div class="notice error" role="alert"><strong>Vérifiez les informations suivantes :</strong><ul>@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
<div class="form-row"><label>Votre nom <span>*</span><input name="name" autocomplete="name" value="{{ old('name') }}" placeholder="Nom et prénom" required maxlength="120"></label><label>Votre organisation<input name="organization" autocomplete="organization" value="{{ old('organization') }}" placeholder="Entreprise, école, ONG…" maxlength="180"></label></div>
<div class="form-row"><label>Votre e-mail <span>*</span><input type="email" name="email" autocomplete="email" value="{{ old('email') }}" placeholder="vous@entreprise.sn" required maxlength="254"></label><label>Votre téléphone<input type="tel" name="phone" autocomplete="tel" value="{{ old('phone') }}" placeholder="+221 …" maxlength="40"></label></div>
<label>Votre besoin <span>*</span><select name="service" required><option value="">Sélectionnez une expertise</option>@foreach(config('aci.services') as $slug => $service)<option value="{{ $slug }}" @selected(old('service', request('service')) === $slug)>{{ $service['title'] }}</option>@endforeach<option value="conseil" @selected(old('service', request('service')) === 'conseil')>Audit, conseil & formation</option></select></label>
<label>Parlez-nous de votre projet <span>*</span><textarea name="message" rows="3" minlength="20" maxlength="5000" required placeholder="Votre contexte, vos besoins, le nombre d’utilisateurs…">{{ old('message') }}</textarea></label>
<div class="honey" aria-hidden="true"><label>Site web<input name="website" tabindex="-1" autocomplete="off"></label></div>
<label class="consent"><input type="checkbox" name="consent" value="1" required @checked(old('consent'))><span>J’accepte que mes informations soient utilisées pour répondre à ma demande. <a href="{{ route('privacy') }}">Confidentialité</a></span></label>
<button type="submit" class="submit-btn">Envoyer ma demande <span>↗</span></button><small class="form-note">* Champs obligatoires. Les demandes sont enregistrées auprès d’ACI Informatique.</small>
</form></div></section>
@endsection